"""
AI Code Guardian v3 — Shared Agent Context Objects
===================================================
Typed structures representing aggregated domain context in AgentWorkflowState.
"""
from __future__ import annotations

from typing import Any, Dict, List, Optional, TypedDict


class RepositoryContext(TypedDict, total=False):
    """Context extracted by RepositoryAgent."""
    languages: List[str]
    frameworks: List[str]
    entry_points: List[str]
    auth_modules: List[str]
    database_layers: List[str]
    infrastructure: List[str]
    public_apis: List[str]
    high_risk_directories: List[str]
    high_value_assets: List[str]
    architecture_type: str
    is_monorepo: bool
    summary: str


class BusinessContextObject(TypedDict, total=False):
    """Context extracted by BusinessAgent."""
    domain: str
    criticality: str
    confidence: float
    critical_assets: List[str]
    compliance_frameworks: List[str]
    business_capabilities: List[str]
    data_classification: str


class SecurityContext(TypedDict, total=False):
    """Context extracted by SecurityAgent."""
    total_findings: int
    severity_counts: Dict[str, int]
    engine_counts: Dict[str, int]
    scanned_files_count: int
    taint_paths_count: int
    secret_findings_count: int
    iac_findings_count: int
    quantum_findings_count: int


class ArchitectureContext(TypedDict, total=False):
    """Context extracted by ArchitectureAgent."""
    service_boundaries: List[str]
    authentication_flows: List[str]
    database_interactions: List[str]
    api_relationships: List[str]
    external_integrations: List[str]
    trust_boundaries: List[str]
    critical_components: List[str]


class DependencyContext(TypedDict, total=False):
    """Context extracted by DependencyAgent."""
    total_dependencies: int
    direct_dependencies_count: int
    transitive_dependencies_count: int
    vulnerable_dependencies_count: int
    manifest_files: List[str]
    detected_libraries: List[Dict[str, Any]]
    cve_list: List[str]


class ThreatContext(TypedDict, total=False):
    """Context derived by ThreatSimulationAgent."""
    exploitability: float
    reachability: float
    attack_paths: List[Dict[str, Any]]
    privilege_escalation_risk: str
    lateral_movement_risk: str
    auth_bypass_risk: str
    data_exposure_risk: str
    business_impact: str


class PolicyResults(TypedDict, total=False):
    """Context derived by PolicyAgent."""
    total_violations: int
    violations: List[Dict[str, Any]]
    passed_policies: List[str]
    failed_policies: List[str]
    overrides: List[Dict[str, Any]]


class RiskProfile(TypedDict, total=False):
    """Composite risk profile calculated by RiskFusionAgent."""
    composite_risk_score: float
    technical_risk_score: float
    business_risk_score: float
    threat_risk_score: float
    policy_risk_score: float
    reachability_weight: float
    confidence_score: float
    risk_level: str


class CorrelatedFindings(TypedDict, total=False):
    """Correlated findings structure generated by EvidenceCorrelationService."""
    total_correlated: int
    chains: List[Dict[str, Any]]
    evidence_mapping: Dict[str, List[str]]
