from typing import List, Dict, Any, Optional, Set
from dataclasses import dataclass
from scanner.intelligence.knowledge_graph import KnowledgeGraph, GraphNode

@dataclass
class ExecutionNode:
    """Lightweight execution domain model for the frontend."""
    id: str
    type: str
    name: str
    snippet: str
    children: List['ExecutionNode']
    metadata: Dict[str, Any] = None

    def to_dict(self):
        return {
            "id": self.id,
            "label": self.name,
            "type": self.type,
            "metadata": self.metadata or {"snippet": self.snippet},
            "children": [c.to_dict() for c in self.children]
        }

class ExecutionTreeBuilder:
    """
    Constructs Application Execution Graphs (file-to-file projection) 
    from the SemanticGraph.
    """

    def __init__(self):
        pass

    def build_global_tree(self, graph: KnowledgeGraph, entry_point_id: str) -> Optional[ExecutionNode]:
        """
        Builds a forward execution tree starting from an entry point.
        """
        return self._traverse_file_execution(graph, entry_point_id, set())

    def _traverse_file_execution(self, graph: KnowledgeGraph, current_file_id: str, visited_files: set) -> Optional[ExecutionNode]:
        if current_file_id in visited_files:
            return None
        
        file_node = graph.get_node(current_file_id)
        if not file_node or file_node.type != "File":
            return None
            
        visited_files.add(current_file_id)
        
        path = file_node.properties.get("path", "")
        name = path.split("/")[-1] if "/" in path else path
        
        exec_node = ExecutionNode(
            id=file_node.id,
            type="File",
            name=name,
            snippet="",
            children=[],
            metadata={"path": path}
        )
        
        # Follow EXECUTES from the file (skip CONTAINS)
        top_level_edges = [e for e in graph.get_out_edges(current_file_id) if e.type == "EXECUTES"]
        
        for edge in top_level_edges:
            child_node = graph.get_node(edge.target_id)
            if not child_node:
                continue
                
            child_exec = self._build_local_exec_tree(graph, child_node.id, visited_files)
            if child_exec:
                exec_node.children.append(child_exec)
                
        # Also find any findings generated directly by the file
        finding_edges = [e for e in graph.get_out_edges(current_file_id) if e.type == "GENERATES_FINDING"]
        for edge in finding_edges:
            finding_node = graph.get_node(edge.target_id)
            if finding_node:
                finding_exec = ExecutionNode(
                    id=finding_node.id,
                    type="Finding",
                    name=finding_node.properties.get("rule_id", "Finding"),
                    snippet=finding_node.properties.get("snippet", ""),
                    children=[],
                    metadata=finding_node.properties
                )
                exec_node.children.append(finding_exec)
                
        return exec_node

    def _build_local_exec_tree(self, graph: KnowledgeGraph, current_id: str, visited_files: set, visited_nodes: set = None) -> Optional[ExecutionNode]:
        if visited_nodes is None:
            visited_nodes = set()
            
        if current_id in visited_nodes:
            return None
            
        visited_nodes.add(current_id)

        node = graph.get_node(current_id)
        if not node:
            return None
            
        name = node.properties.get("name", node.type)
        if node.type == "Function":
            if not name.endswith("()"):
                name = f"{name}()"
        elif node.type == "Call":
            if not name.endswith("()"):
                name = f"{name}()"
        elif node.type == "Finding":
            name = node.properties.get("rule_id", "Finding")
            
        exec_node = ExecutionNode(
            id=node.id,
            type=node.type,
            name=name,
            snippet=node.properties.get("snippet", ""),
            children=[],
            metadata=node.properties
        )
        
        # 1. Add nested items by following EXECUTES (skip CONTAINS)
        nested_edges = [e for e in graph.get_out_edges(current_id) if e.type == "EXECUTES"]
        for edge in nested_edges:
            child_tree = self._build_local_exec_tree(graph, edge.target_id, visited_files, visited_nodes.copy())
            if child_tree:
                exec_node.children.append(child_tree)
                
        # 2. Add security findings generated by this function/element
        finding_edges = [e for e in graph.get_out_edges(current_id) if e.type == "GENERATES_FINDING"]
        for edge in finding_edges:
            finding_node = graph.get_node(edge.target_id)
            if finding_node:
                finding_exec = ExecutionNode(
                    id=finding_node.id,
                    type="Finding",
                    name=finding_node.properties.get("rule_id", "Finding"),
                    snippet=finding_node.properties.get("snippet", ""),
                    children=[],
                    metadata=finding_node.properties
                )
                exec_node.children.append(finding_exec)
                
        # 3. Add cross-file and same-file execution calls/transitions (CALLS, ROUTES_TO)
        transition_edges = [e for e in graph.get_out_edges(current_id) if e.type in ("CALLS", "ROUTES_TO")]
        for edge in transition_edges:
            target_node = graph.get_node(edge.target_id)
            if not target_node:
                continue
                
            target_file_id = self._get_parent_file(graph, target_node.id)
            current_file_id = self._get_parent_file(graph, current_id)
            
            if target_file_id and current_file_id and target_file_id != current_file_id:
                # Cross-file: wrap the target in a File node so it shows the file boundary
                if target_file_id not in visited_files:
                    visited_files.add(target_file_id)
                    curr_file_node = graph.get_node(target_file_id)
                    
                    if curr_file_node:
                        file_path = curr_file_node.properties.get("path", "")
                        file_exec = ExecutionNode(
                            id=curr_file_node.id,
                            type="File",
                            name=file_path.split("/")[-1] if "/" in file_path else file_path,
                            snippet="",
                            children=[],
                            metadata={"path": file_path}
                        )
                        
                        # Now trace into the target function/element
                        target_exec = self._build_local_exec_tree(graph, target_node.id, visited_files, visited_nodes.copy())
                        if target_exec:
                            # Inject Class node if the target is a Function inside a Class
                            if target_node.type == "Function":
                                parent_id = target_node.properties.get("parent_id")
                                if parent_id:
                                    parent_node = graph.get_node(parent_id)
                                    if parent_node and parent_node.type == "Class":
                                        class_exec = ExecutionNode(
                                            id=parent_node.id,
                                            type="Class",
                                            name=parent_node.properties.get("name", "Class"),
                                            snippet=parent_node.properties.get("snippet", ""),
                                            children=[target_exec],
                                            metadata=parent_node.properties
                                        )
                                        target_exec = class_exec
                                        
                            file_exec.children.append(target_exec)
                        exec_node.children.append(file_exec)
            else:
                # Same-file: trace into the target function/element directly
                target_exec = self._build_local_exec_tree(graph, target_node.id, visited_files, visited_nodes.copy())
                if target_exec:
                    # Inject Class node if the target is a Function inside a Class
                    if target_node.type == "Function":
                        for in_edge in graph.get_in_edges(target_node.id):
                            if in_edge.type == "CONTAINS":
                                parent_node = graph.get_node(in_edge.source_id)
                                if parent_node and parent_node.type == "Class":
                                    class_exec = ExecutionNode(
                                        id=parent_node.id,
                                        type="Class",
                                        name=parent_node.properties.get("name", "Class"),
                                        snippet=parent_node.properties.get("snippet", ""),
                                        children=[target_exec],
                                        metadata=parent_node.properties
                                    )
                                    target_exec = class_exec
                                    break
                                
                    exec_node.children.append(target_exec)
                    
        return exec_node

    def build_path(self, graph: KnowledgeGraph, sink_id: str) -> Optional[ExecutionNode]:
        """
        Builds a reverse execution path from a finding/sink back to its entry point.
        """
        sink_node = graph.get_node(sink_id)
        if not sink_node:
            return None

        path_list = self._traverse_backwards_files(graph, sink_id, set())
        if not path_list:
            return None
            
        path_list.reverse()
        
        # Filter consecutive duplicates
        dedup_path = []
        for node in path_list:
            if not dedup_path or dedup_path[-1].id != node.id:
                dedup_path.append(node)
                
        if not dedup_path:
            return None
            
        # 1. While execution moves between modules, display ONLY File nodes.
        # 2. Do NOT expand classes/functions for intermediate files.
        # 3. Only the FINAL destination file expands into: File -> Class -> Function -> Finding.
        
        last_file_idx = -1
        for i in range(len(dedup_path) - 1, -1, -1):
            if dedup_path[i].type == "File":
                last_file_idx = i
                break

        # FIX 2: Strip noise nodes (Repository, Import, Call) from the pre-last-File
        # section. These accumulate from the fallback chain and CONTAINS traversal.
        # Only File nodes should appear in the inter-module section of the path.
        _DISPLAY_ONLY_BEFORE_LAST_FILE = {"File"}
                
        filtered_path = []
        if last_file_idx != -1:
            # Everything before the last File node: keep ONLY File nodes
            for node in dedup_path[:last_file_idx]:
                if node.type in _DISPLAY_ONLY_BEFORE_LAST_FILE:
                    filtered_path.append(node)
                    
            # For the final destination file, we only want: File -> Class -> Function -> Finding
            final_nodes = dedup_path[last_file_idx:]
            file_node = final_nodes[0]
            finding_node = final_nodes[-1] if final_nodes[-1].type == "Finding" else None
            
            # Find the closest Function to the Finding
            func_node = None
            for node in reversed(final_nodes):
                if node.type == "Function":
                    func_node = node
                    break
                    
            # Find the closest Class to the Function
            class_node = None
            for node in reversed(final_nodes):
                if node.type == "Class":
                    class_node = node
                    break
                    
            filtered_path.append(file_node)
            if class_node:
                filtered_path.append(class_node)
            if func_node:
                filtered_path.append(func_node)
            if finding_node:
                filtered_path.append(finding_node)
        else:
            filtered_path = dedup_path
        app_node = ExecutionNode(
            id="execution_root",
            type="Application",
            name="Application",
            snippet="",
            children=[],
            metadata={}
        )
        
        root = app_node
        current = root
        for node in filtered_path:
            node.children = []
            current.children.append(node)
            current = node
            
        return root

    def _traverse_backwards_files(self, graph: KnowledgeGraph, current_id: str, visited: set) -> List[ExecutionNode]:
        if current_id in visited:
            return []
        visited.add(current_id)
        
        current_node = graph.get_node(current_id)
        if not current_node:
            return []

        path_nodes = []
        
        # Create the execution step representation for the current node
        name = current_node.properties.get("name", current_node.type)
        if current_node.type == "Function":
            if not name.endswith("()"):
                name = f"{name}()"
            node_exec = ExecutionNode(
                id=current_node.id,
                type="Function",
                name=name,
                snippet=current_node.properties.get("snippet", ""),
                children=[],
                metadata=current_node.properties
            )
            path_nodes.append(node_exec)
            
            # Inject Class node if contained in a class
            for in_edge in graph.get_in_edges(current_id):
                if in_edge.type == "CONTAINS":
                    parent = graph.get_node(in_edge.source_id)
                    if parent and parent.type == "Class":
                        class_exec = ExecutionNode(
                            id=parent.id,
                            type="Class",
                            name=parent.properties.get("name", "Class"),
                            snippet=parent.properties.get("snippet", ""),
                            children=[],
                            metadata=parent.properties
                        )
                        path_nodes.append(class_exec)
                        break
        elif current_node.type == "Call":
            if not name.endswith("()"):
                name = f"{name}()"
        elif current_node.type == "Finding":
            name = current_node.properties.get("rule_id", "Finding")
            
        if current_node.type == "File":
            path = current_node.properties.get("path", "")
            node_exec = ExecutionNode(
                id=current_node.id,
                type="File",
                name=path.split("/")[-1] if "/" in path else path,
                snippet="",
                children=[],
                metadata={"path": path}
            )
            path_nodes.append(node_exec)
        elif current_node.type == "Class":
            # FIX 3: Class nodes are already injected during the Function step above.
            # When we arrive at a Class node directly (via CONTAINS fallback from its
            # contained Function), do NOT emit it again — it was already added.
            # We still search for predecessors, so path_nodes stays empty here.
            pass
        elif current_node.type != "Function":
            node_exec = ExecutionNode(
                id=current_node.id,
                type=current_node.type,
                name=name,
                snippet=current_node.properties.get("snippet", ""),
                children=[],
                metadata=current_node.properties
            )
            path_nodes.append(node_exec)

        in_edges = graph.get_in_edges(current_id)
        priority_types = ["CALLS", "ROUTES_TO", "EXECUTES", "GENERATES_FINDING", "IMPORTS", "RESOLVES_TO"]
        
        sorted_edges = sorted(in_edges, key=lambda e: priority_types.index(e.type) if e.type in priority_types else 99)
        
        best_path = []
        for edge in sorted_edges:
            if edge.type in priority_types:
                
                # Inject parent file if we cross a file boundary backward
                parent_file_id = self._get_parent_file(graph, edge.source_id)
                current_file_id = self._get_parent_file(graph, current_id)
                
                additional_nodes = []
                if parent_file_id and current_file_id and parent_file_id != current_file_id:
                    curr_file_node = graph.get_node(current_file_id)
                    if curr_file_node:
                        file_path = curr_file_node.properties.get("path", "")
                        file_exec = ExecutionNode(
                            id=curr_file_node.id,
                            type="File",
                            name=file_path.split("/")[-1] if "/" in file_path else file_path,
                            snippet="",
                            children=[],
                            metadata={"path": file_path}
                        )
                        additional_nodes.append(file_exec)

                parent_path_list = self._traverse_backwards_files(graph, edge.source_id, visited.copy())
                if parent_path_list:
                    candidate_path = additional_nodes + parent_path_list
                    if len(candidate_path) > len(best_path):
                        best_path = candidate_path

        if best_path:
            return path_nodes + best_path
            
        # FIX 1: If we are stuck at a File node, check if any of its children
        # have incoming RESOLVES_TO or CALLS edges that can lead us to a predecessor.
        # CRITICAL: exhaust ALL children — do NOT break on the first empty result.
        if current_node.type == "File":
            child_best_path = []
            for c_edge in graph.get_out_edges(current_id):
                if c_edge.type not in ("CONTAINS", "EXECUTES"):
                    continue
                child_id = c_edge.target_id
                for grand_in_edge in graph.get_in_edges(child_id):
                    if grand_in_edge.type not in ("RESOLVES_TO", "CALLS"):
                        continue
                    candidate = self._traverse_backwards_files(graph, grand_in_edge.source_id, visited.copy())
                    if candidate and len(candidate) > len(child_best_path):
                        child_best_path = candidate
            if child_best_path:
                return path_nodes + child_best_path
        
        # If we are stuck at a Function or Class node, try climbing up CONTAINS edges 
        # to the parent File, where we might find execution edges (like routes) pointing to it.
        elif current_node.type in ("Function", "Class"):
            parent_id = self._get_immediate_parent(graph, current_id)
            if parent_id and parent_id != current_id:
                parent_path_list = self._traverse_backwards_files(graph, parent_id, visited.copy())
                if parent_path_list:
                    # Don't duplicate the parent file node if it's already in path_nodes
                    return path_nodes + parent_path_list

        # Fallback to the originating parent (Class or File) for any other type
        parent_id = self._get_immediate_parent(graph, current_id)
        if parent_id and parent_id != current_id:
            parent_path_list = self._traverse_backwards_files(graph, parent_id, visited.copy())
            if parent_path_list:
                return path_nodes + parent_path_list
                
        return path_nodes

    def _get_immediate_parent(self, graph: KnowledgeGraph, node_id: str) -> Optional[str]:
        for edge in graph.get_in_edges(node_id):
            if edge.type in ("CONTAINS", "EXECUTES"):
                return edge.source_id
        return None

    def find_entry_points(self, graph: KnowledgeGraph) -> List[Dict[str, str]]:
        entry_points = []
        entry_file_names = ["main.py", "app.py", "server.py", "manage.py", "index.js", "app.js", "server.js", "main.go"]
        
        for node in graph.nodes.values():
            if node.type == "File":
                path = node.properties.get("path", "")
                if any(path.endswith(name) for name in entry_file_names):
                    entry_points.append({
                        "id": node.id,
                        "path": path,
                        "name": path.split("/")[-1] if "/" in path else path
                    })
        return entry_points

    # --- Helpers ---
    def _get_contained_nodes(self, graph: KnowledgeGraph, node_id: str) -> Set[str]:
        contained = set()
        for edge in graph.get_out_edges(node_id):
            if edge.type in ("CONTAINS", "EXECUTES"):
                if edge.target_id not in contained:
                    contained.add(edge.target_id)
                    contained.update(self._get_contained_nodes(graph, edge.target_id))
        return contained

    def _get_parent_file(self, graph: KnowledgeGraph, node_id: str) -> str:
        curr_id = node_id
        visited = set()
        while curr_id and curr_id not in visited:
            visited.add(curr_id)
            node = graph.get_node(curr_id)
            if node and node.type == "File":
                return curr_id
            found_parent = False
            for edge in graph.get_in_edges(curr_id):
                if edge.type in ("CONTAINS", "EXECUTES"):
                    curr_id = edge.source_id
                    found_parent = True
                    break
            if not found_parent:
                break
        return None
