import json
import logging
import os
from typing import Dict, List
from urllib import response
from scanner.language_learning.nemotron_llm import NemotronLLM
from dotenv import load_dotenv
from rag.prompts import SECURITY_ANALYST_PROMPT

logging.basicConfig(level=logging.INFO)

load_dotenv()


class SecurityLLM:
    """
    Handles interaction with the Nemotron model.
    """

    def __init__(self):

        api_key = os.getenv("NVIDIA_API_KEY") 

        if not api_key:
            raise ValueError(
                "NVIDIA_API_KEY not found in .env"
            )

        self.client = NemotronLLM()

        # self.model = os.getenv(
        #     "LLM_MODEL",
        #     "gemini-2.5-flash"
        # )

    # --------------------------------------------------

    def _build_context(
        self,
        retrieved_docs: List[Dict]
    ) -> str:

        context = []

        for doc in retrieved_docs:

            context.append(
                f"""
Source:
{doc['source']}

Vulnerability:
{doc['vulnerability']}

Description:
{doc['description']}

Recommendation:
{doc['recommendation']}

Reference:
{doc['url']}

Relevance Score:
{doc.get("score", "N/A")}
"""
            )

        return "\n\n".join(context)

    # --------------------------------------------------

    def generate(
        self,
        finding: Dict,
        retrieved_docs: List[Dict]
    ) -> Dict:

        context = self._build_context(retrieved_docs)

        prompt = SECURITY_ANALYST_PROMPT.format(
            context=context,
            category=finding["category"],
            severity=finding["severity"],
            language=finding.get("language", "Python"),
            description=finding.get("description", ""),
            snippet=finding["snippet"],
        )

        logging.info("Generating AI explanation...")

        system_prompt = (
            "You are an expert Application Security Engineer.\n\n"
            "Return ONLY valid JSON in this format:\n"
            "{\n"
            '  "why": "...",\n'
            '  "fix": "...",\n'
            '  "references": ["..."]\n'
            "}\n"
            "Do not wrap in markdown."
        )

        text = self.client.generate(
    prompt=prompt,
    system_prompt=system_prompt,
)

        # Remove markdown fences if Gemini adds them
        if text.startswith("```"):
            text = text.replace("```json", "").replace("```", "").strip()

        try:
            result = json.loads(text)
        except Exception:
            logging.exception("Failed to parse NVIDIA output.")
            logging.error(text)

            return {
                "why": "Unable to generate explanation.",
                "fix": "No remediation generated.",
                "references": [],
            }

        return {
            "why": result.get(
                "why",
                "No explanation generated by the model."
            ),
            "fix": result.get(
                "fix",
                "No remediation generated by the model."
            ),
            "references": result.get(
                "references",
                []
            ),
        }

    # --------------------------------------------------

    def chat(self, prompt: str) -> str:
        """
        Generic chat interface for the conversational assistant.
        """

        system_prompt = (
            "You are AI Code Guardian, an expert application security assistant."
        )

        return self.client.generate(
    prompt=prompt,
    system_prompt=system_prompt,
)