import sys
import os

_PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
if _PROJECT_ROOT not in sys.path:
    sys.path.insert(0, _PROJECT_ROOT)

from scanner.models import SecurityFinding, FunctionSymbol, ClassSymbol, CallSymbol, ParsedFile
from scanner.intelligence.knowledge_graph import KnowledgeGraphBuilder
from scanner.intelligence.tree_service import TreeService
from scanner.intelligence.execution_builder import ExecutionTreeBuilder

# Build a chain of calls across files
f1 = ParsedFile(file_path='main.py', language='Python')
f1.functions.append(FunctionSymbol(name='main', line=1, snippet='def main():', symbol_id='f1_main'))
f1.calls.append(CallSymbol(name='start', line=2, snippet='start()', symbol_id='f1_call', parent_id='f1_main'))

f2 = ParsedFile(file_path='app.py', language='Python')
f2.functions.append(FunctionSymbol(name='start', line=1, snippet='def start():', symbol_id='f2_start'))
f2.calls.append(CallSymbol(name='run', line=2, snippet='run()', symbol_id='f2_call', parent_id='f2_start'))

f3 = ParsedFile(file_path='db.py', language='Python')
f3.functions.append(FunctionSymbol(name='run', line=1, snippet='def run():', symbol_id='f3_run'))
f3.calls.append(CallSymbol(name='query', line=2, snippet='query()', symbol_id='f3_call', parent_id='f3_run'))

finding = SecurityFinding(
    rule_id='sql_injection', title='SQL Injection', category='Injection', severity='Critical',
    confidence=0.95, file='db.py', line=2, class_name='', function_name='run',
    snippet='query()', evidence='none', cwe='CWE-89', owasp='A1', recommendation='fix it',
    symbol_id='f3_run'
)

kg = KnowledgeGraphBuilder("repo")
graph = kg.build([f1, f2, f3], [finding])

# Link them! (The parser would normally do this, we do it manually for the test graph)
graph.add_edge('f1_call', 'f2_start', 'CALLS')
graph.add_edge('f2_call', 'f3_run', 'CALLS')
# And the finding is generated by f3_run. KnowledgeGraphBuilder auto-adds GENERATES_FINDING.

print("Edges added manually")

builder = ExecutionTreeBuilder()

# Patch traversal to print debug info
original_traverse = builder._traverse_backwards_files
def debug_traverse(self, graph, current_id, visited):
    print(f"\nVisiting: {current_id}")
    node = graph.get_node(current_id)
    if not node:
        print(f"  STOP: Node {current_id} not found in graph")
        return []
        
    print(f"  Type: {node.type}")
    
    in_edges = graph.get_in_edges(current_id)
    priority_types = ["CALLS", "ROUTES_TO", "EXECUTES", "GENERATES_FINDING"]
    sorted_edges = sorted(in_edges, key=lambda e: priority_types.index(e.type) if e.type in priority_types else 99)
    
    in_exec = [e for e in in_edges if e.type in priority_types]
    print(f"  Incoming priority edges: {[e.source_id + ' (' + e.type + ')' for e in in_exec]}")
    print(f"  Outgoing priority edges: {[e.target_id + ' (' + e.type + ')' for e in graph.get_out_edges(current_id) if e.type in priority_types]}")
    
    res = original_traverse(graph, current_id, visited)
    
    if not in_exec:
        print(f"  STOP: No incoming execution edges. Fallback triggered?")
    else:
        print(f"  CONTINUE: Found {len(in_exec)} incoming execution edges.")
        
    return res

ExecutionTreeBuilder._traverse_backwards_files = debug_traverse

print("\n\n=== RUNNING TRAVERSAL ===")
builder._traverse_backwards_files(graph, finding.finding_id, set())
